### ISSUE TITLE
Systembar isn't scaled correctly (depends on Device)

### ISSUE THREAD

**Issue by Felix-Helleckes** [frokmosoftware/FSLauncher#1]
**Describe the bug**
The Systembar for App Shortcuts is on Devices which has mechanical Home Buttons scaling wrong
**To Reproduce**
1. Install FS Launcher
2. Just Check Homescreen (Screenshot)

**Expected behavior**
Systembar like on every other phone
**Screenshots**
![screenshot_20181011-103808](https://user-images.githubusercontent.com/44090741/46869244-63517b00-ce2b-11e8-87d2-fcf4661c9e4d.png)

**Other information (please complete the following information):**
 - OS-Version: [Android 7]
 - Device: Samsung Galaxy S6 
 - App-Version [beta 1.0]

**Additional information**
Add any other information about the problem here.

**Comment by frokmosoftware** [comment]
@Sparky512 This should be fixed in version `beta-1.0.1`, thanks for reporting!

**Comment by Felix-Helleckes** [comment]
Thank you for the fast Fix. Working as expected right now.
